project_name: aiges 
gomod:
  # Proxy a module from proxy.golang.org, making the builds verifiable.
  # This will only be effective if running against a tag. Snapshots will ignore this setting.
  # Notice: for this to work your `build.main` must be a package, not a `.go` file.
  #
  # Default is false.
  proxy: false

  # If proxy is true, use these environment variables when running `go mod` commands (namely, `go mod tidy`).
  # Defaults to `os.Environ()`.
  env:
    - GOPROXY=https://goproxy.cn

before:
  hooks:
    # You may remove this if you don't use go modules.
    -  go mod vendor
builds:
  - env:
      - CGO_ENABLED=1
      - CC=x86_64-linux-gnu-gcc
      - CC_FOR_TARGET=gcc-x86_64-linux-gnu
      - PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig/
    main: ./main
    id: aiges
    hooks:
      pre:
       - sudo apt-get install -y libnuma-dev
       - mkdir -p {{ dir .Path }}/include
       - cp -ar ./cgo/library/ {{ dir .Path }}/
       - cp -ar ./cgo/header/widget/  {{ dir .Path }}/include/
    binary: AIservice
    goos:
      - linux
    goarch:
      - amd64
    tags:
      - netgo
      - static
      - osusergo
    ldflags:
      # - -X github.com/labring/sealos/pkg/version.gitVersion={{.Version}}
      # - -X github.com/labring/sealos/pkg/version.gitCommit={{.ShortCommit}}
      # - -X github.com/labring/sealos/pkg/version.buildDate={{.Date}}
      # - -extldflags "-static -fpic"
      - -s -w
      - -linkmode external

  - env:
      - CGO_ENABLED=1
      - CC=x86_64-linux-gnu-gcc
      - CC_FOR_TARGET=gcc-x86_64-linux-gnu
      - PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig/
    main: ./xtest/main
    id: xtest
    hooks:
      pre:
        - sudo apt-get install -y libnuma-dev
        - cp -ar ./xtest/script/xtest.toml {{ dir .Path }}/
        - cp -ar ./xtest/script/test.sh  {{ dir .Path }}/
    binary: xtest
    goos:
      - linux
    goarch:
      - amd64
    tags:
      - netgo
      - static
      - osusergo
    ldflags:
      # - -X github.com/labring/sealos/pkg/version.gitVersion={{.Version}}
      # - -X github.com/labring/sealos/pkg/version.gitCommit={{.ShortCommit}}
      # - -X github.com/labring/sealos/pkg/version.buildDate={{.Date}}
      # - -extldflags "-static -fpic"
      - -s -w
      - -linkmode external

archives:
  -
   files:
     - src: './cgo/library/*'
       dst: 'library'
       strip_parent: true

#        # Strip parent folders when adding files to the archive.
#        # Default: false
#        strip_parent: false
     - src: './cgo/header/widget/*'
       dst: 'include'
       strip_parent: true
#        # Strip parent folders when adding files to the archive.
#        # Default: false
#  - replacements:
#      darwin: Darwin
#      linux: Linux
#      amd64: x86_64
#      arm64: aarch64
checksum:
  disable: true
  name_template: '{{ .ProjectName }}_checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

