FROM artifacts.iflytek.com/docker-private/jianjiang/ubuntu_go:20.04_1.16 as go-builder
MAINTAINER ybyang7@iflytek.com

ENV GOPROXY=https://goproxy.cn,direct
RUN apt-get update && apt-get install -y libnuma-dev build-essential git
COPY . /home/aiges
WORKDIR /home/aiges

#RUN mkdir -p output/include && go mod vendor && go build -v -o ./output/AIservice -gcflags "-N -l -c 10" main/main.go && \
#    cp ./cgo/header/widget/* ./output/include/ && \
#    cp  -r ./cgo/library/* ./output/

RUN make build-pack

FROM artifacts.iflytek.com/docker-private/atp/python:3.9.12-bullseye as cpython-builder
MAINTAINER ybyang7@iflytek.com

RUN echo '''deb https://mirrors.aliyun.com/debian/ bullseye main non-free contrib \
deb-src https://mirrors.aliyun.com/debian/ bullseye main non-free contrib \
deb https://mirrors.aliyun.com/debian-security/ bullseye-security main \
deb-src https://mirrors.aliyun.com/debian-security/ bullseye-security main \
deb https://mirrors.aliyun.com/debian/ bullseye-updates main non-free contrib \
deb-src https://mirrors.aliyun.com/debian/ bullseye-updates main non-free contrib \
deb https://mirrors.aliyun.com/debian/ bullseye-backports main non-free contrib \
deb-src https://mirrors.aliyun.com/debian/ bullseye-backports main non-free contrib''' >/etc/apt/sources.list

WORKDIR /home/loader
RUN apt update && apt install -y build-essential vim


RUN DEBIAN_FRONTEND=noninteractive apt update &&apt install -y libnuma-dev libboost-all-dev
COPY ai_cpython_wrapper/ /home/wrapper

RUN cd /home/wrapper && make

#ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/aiges:/home/wrapper/wrappere_lib

FROM artifacts.iflytek.com/docker-private/atp/python:3.9.12-bullseye as final
MAINTAINER ybyang7@iflytek.com
ENV TZ Asia/Shanghai
RUN echo '''deb https://mirrors.aliyun.com/debian/ bullseye main non-free contrib \
deb-src https://mirrors.aliyun.com/debian/ bullseye main non-free contrib \
deb https://mirrors.aliyun.com/debian-security/ bullseye-security main \
deb-src https://mirrors.aliyun.com/debian-security/ bullseye-security main \
deb https://mirrors.aliyun.com/debian/ bullseye-updates main non-free contrib \
deb-src https://mirrors.aliyun.com/debian/ bullseye-updates main non-free contrib \
deb https://mirrors.aliyun.com/debian/ bullseye-backports main non-free contrib \
deb-src https://mirrors.aliyun.com/debian/ bullseye-backports main non-free contrib''' >/etc/apt/sources.list

RUN DEBIAN_FRONTEND=noninteractive apt update &&apt install -y libnuma-dev libboost-all-dev
ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/aiges:/home/aiges/library
WORKDIR /home/aiges
COPY --from=go-builder /home/aiges/dist/aiges_linux_amd64 .
COPY --from=cpython-builder /home/wrapper/wrapper_lib /home/aiges/library
