version: "3"
services:
  hermes:
    image: 172.16.59.153/aiaas/hermes:0.0.0
    network_mode: "host"
    restart: "no"
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    volumes:
      - ${PWD}/cli1:/xsf/perf/client/log
    entrypoint: './lbv2'
    command: '-m 1 -c lbv2.toml -p xsf -s xsf-lbv2 -u http://companion.xfyun.iflytek:6868 -g xsf'