[lbv2]
host="0.0.0.0"                 #若host为空，则取netcard对应的ip，若二者均为空，则取hostname对应的ip
#netcard = "eth0"
port = 1995                       #指定端口
reuseport = 0                     #缺省0
cmdserver = 0                     #缺省0
finder = 0                        #使用服务发现,缺省0

[bo]#Business Object
#pprof = 9999 #缺省关闭pprof
strategy = 0                      #策略 0：load  1: poll 2: loadMini
threshold = 90                    #服务阈值，(totalInst - idleInst) * 100 / totalInst
ticker = 5000                    #清除无效节点的扫描周期，单位毫秒
svc = "iat"                       #后续可优化
defsub = "sms-2s"                    #兜底路由
ttl = 3000                      #节点的生存周期,单位毫秒
#preauth = 8  #预授开关，缺省预授-1
rmqable = 0 #缺省1，开启
rmqaddrs = "172.16.154.26:10700,172.16.154.26:10800,172.16.154.26:10900"
#rmqaddrs = "10.1.87.19:10800,10.1.87.68:10800"
rmqtopic = "mc_iat_test"
rmqgroup = "group"
rmqticker = 1000 #消费rmq的时间间隔
consumer = 3
monitor = 1000 #监控数据的更新周期，单位毫秒
nodedur = 10000 #异常节点的保存周期，单位毫秒

[db]
able = 0 #缺省1
batch = 2#每次最多从数据库拉取的数据条数，缺省10000
baseurl   = "http://172.16.154.235:808/ws"
caller    = "xfyun"
callerkey = "12345678"
timeout   = 3000 #毫秒
token     = "100IME"
version   = "db-service-v3-3.0.0.1001"
idc       = "bj"
schema    = "ifly_cp_msp_balance"
table     = "seg_list_lbv2"
dbtime    = 1 #清理db的时间间隔，缺省172800s，单位s
rctime    = 1 #第一次访问db失败后，后续重新访问数据的时间间隔，缺省600s

[dc]#通知ats拉取个性化资源所用
#测试目标服务配置，配置格式如下,注意分割符的差异
#业务1@ip1:port1;ipn:portn,业务2@ip2:port2;ipn:portn
conn-timeout = 100
conn-pool-size = 4         #rpc连接池数量。缺省4
lb-mode= 0  #0禁用lb,2使用lb。缺省0
lb-retry = 0
#taddrs="lbv2@10.1.87.61:9095"

[trace]
host = "172.16.51.3"              #trace收集服务的地址,缺省127.0.0.1
port = 4546                       #trance的端口号,缺省4545
backend = 1                       #trace服务的协程数,缺省4
deliver = 1                       #是否将日志写入到远端,缺省1
dump = 1                          #是否将日志 落入磁盘,缺省0
able = 0                          #是否禁用trace,缺省1

[log]
level = "debug"                  #日志文件类型,缺省warn
file = "log/lb.log"              #日志文件名,缺省xsfs.log
size = 100                         #日志文件的大小,单位MB,缺省10
count = 10                        #日志文件的备份数量,缺省10
die = 3                          #日志文件的有效期,单位Day,缺省10
cache = -1                       #缓存大小,单位条数,超过会丢弃,(缺省-1，代表不丢数据，堆积到内存)
batch = 1600                     #批处理大小,单位条数,一次写入条数（触发写事件的条数）
async = 0                        #异步日志,缺省异步
caller = 1                       #是否添加调用行信息,缺省0

[sonar]
host = "10.1.86.60"              #trace收集服务的地,缺省127.0.0.1
port = 4546                      #trace收集服务的端口,缺省4545
backend = 1                      #trace服务的协程数,缺省4
deliver = 1                      #是否将日志写入到远端,缺省1
dump = 1                         #是否将日志写入磁盘,缺省0
able = 0                         #是否禁用trace,缺省1
rate = 5000                      #上报频率,单位毫秒
ds = "vagus"                     #缺省vagus