Collections:
- Name: SegOCR
  Metadata:
    Training Data: mixture
    Training Techniques:
      - Adam
    Epochs: 5
    Batch Size: 64
    Training Resources: 4x GeForce GTX 1080 Ti
    Architecture:
      - ResNet31OCR
      - FPNOCR
  Paper:
  README: configs/textrecog/seg/README.md

Models:
  - Name: seg_r31_1by16_fpnocr_academic
    In Collection: SegOCR
    Config: configs/textrecog/seg/seg_r31_1by16_fpnocr_academic.py
    Metadata:
      Training Data: SynthText
    Results:
      - Task: Text Recognition
        Dataset: IIIT5K
        Metrics:
          word_acc: 90.9
      - Task: Text Recognition
        Dataset: SVT
        Metrics:
          word_acc: 81.8
      - Task: Text Recognition
        Dataset: ICDAR2013
        Metrics:
          word_acc: 90.7
      - Task: Text Recognition
        Dataset: CT80
        Metrics:
          word_acc: 80.9
    Weights: https://download.openmmlab.com/mmocr/textrecog/seg/seg_r31_1by16_fpnocr_academic-72235b11.pth
