FROM artifacts.iflytek.com/docker-private/atp/aiges-gpu:10.1-3.9.13-ubuntu1804-v1.0.0

RUN  pip3 config set global.index-url https://pypi.mirrors.ustc.edu.cn/simple/ 

RUN pip3 install torch==1.10  torchvision 
RUN  apt install -y  libgl1-mesa-glx && pip3 install openmim && \
    mim install mmcv-full && \
    mim install mmdet==2.24.0

copy mmocr /home/mmocr

RUN cd /home/mmocr/ && pip3 install -e .
RUN pip3 install iflags



COPY wrapper.py /home/mmocr

# 拷贝mmocr配置文件到  /home/aiges, 因为工作目录位于 /home/aiges
RUN cp -ra /home/mmocr/configs /home/aiges


ENV PYTHONPATH=$PYTHONPATH:/home/mmocr

ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/wrapper/wrapper_lib


COPY xtest.toml /home/aiges
COPY xtest /home/aiges/xtest
COPY aiges.toml /home/aiges
CMD ["sh", "-c", "./AIservice -m=0 -c=aiges.toml -s=svcName -u=http://companion.xfyun.iflytek:6868 -p=AIaaS -g=dx"]
