#服务自身的配置
#注意此section名需对应bootConfig中的service
#----------------------------------------服务端------------------------------------------------------------
[webgate-ws-svc]#已做缺省处理
#host = "127.0.0.1"#若host为空，则取netcard对应的ip，若二者均为空，则取hostname对应的ip
#host = "10.1.107.8"
#netcard = "eth0"
port = 9027
finder = 1 #缺省0
debug  = 0 #缺省0

[log]#已做缺省处理
level = "error" #缺省warn
file = "/log/server/xsf.log" #缺省xsfs.log
#日志文件的大小，单位MB
size = 300 #缺省10
#日志文件的备份数量
count = 3 #缺省10
#日志文件的有效期，单位Day
die = 3 #缺省10
#缓存大小，单位条数,超过会丢弃
cache = 100000 #缺省-1，代表不丢数据，堆积到内存中
#批处理大小，单位条数，一次写入条数（触发写事件的条数）
batch = 160#缺省16*1024
#异步日志
async = 1 #缺省异步
#是否添加调用行信息
caller = 1 #缺省0
wash = 60 #写入磁盘的缺省时间

[trace]
host = "127.0.0.1"
port = 4545 #缺省4545
able = 1              #开启trace
dump = 0
bcluster = "5s"
idc = "dz"
deliver = 1          #是否开启网络发包
watch = 1
watchport = 10000
loadts = 10
spill-able=0
backend = 10
buffer=2000
#taddrs="svc@10.1.205.151:50051;10.1.205.151:50052,svc@10.1.205.151:50052;10.1.205.151:50051"

#######------------------------------客户端-----------------------------------------------------
[webgate-ws-c]
#测试目标服务配置，配置格式如下,注意分割符的差异
#业务1@ip1:port1;ipn:portn,业务2@ip2:port2;ipn:portn
#taddrs="svc@10.1.205.151:50051;10.1.205.151:50052,svc@10.1.205.151:50052;10.1.205.151:50051"

conn-timeout = 3000
lb-mode= 0
lb-retry = 2
#taddrs="xsf@10.1.87.18:50061,sms@10.1.87.21:5091"
#taddrs="xsf@172.21.210.66:8684,sms@10.1.87.21:5091"
#taddrs="xsf@10.1.87.70:8997,sms@10.1.87.21:5091"
#taddrs="atmos-svc@10.1.87.66:9119"
#taddrs="atmos@10.1.87.19:27178"
#taddrs="xsf@10.1.87.116:9988,sms@172.16.154.177:5091"
#taddrs="xsf@172.16.154.172:50062,sms@172.16.154.177:5091"
[sonar]
dump=0 #是否开启保存数据到磁盘

ds="vagus_null"