Collections:
- Name: NRTR
  Metadata:
    Training Data: OCRDataset
    Training Techniques:
      - Adam
    Epochs: 6
    Batch Size: 6144
    Training Resources: 48x GeForce GTX 1080 Ti
    Architecture:
      - CNN
      - NRTREncoder
      - NRTRDecoder
  Paper:
    URL: https://arxiv.org/pdf/1806.00926.pdf
    Title: 'NRTR: A No-Recurrence Sequence-to-Sequence Model For Scene Text Recognition'
  README: configs/textrecog/nrtr/README.md

Models:
  - Name: nrtr_r31_1by16_1by8_academic
    In Collection: NRTR
    Config: configs/textrecog/nrtr/nrtr_r31_1by16_1by8_academic.py
    Metadata:
      Training Data:
        - SynthText
        - Syn90k
    Results:
      - Task: Text Recognition
        Dataset: IIIT5K
        Metrics:
          word_acc: 94.7
      - Task: Text Recognition
        Dataset: SVT
        Metrics:
          word_acc: 87.3
      - Task: Text Recognition
        Dataset: ICDAR2013
        Metrics:
          word_acc: 94.3
      - Task: Text Recognition
        Dataset: ICDAR2015
        Metrics:
          word_acc: 73.5
      - Task: Text Recognition
        Dataset: SVTP
        Metrics:
          word_acc: 78.9
      - Task: Text Recognition
        Dataset: CT80
        Metrics:
          word_acc: 85.1
    Weights: https://download.openmmlab.com/mmocr/textrecog/nrtr/nrtr_r31_1by16_1by8_academic_20211124-f60cebf4.pth

  - Name: nrtr_r31_1by8_1by4_academic
    In Collection: NRTR
    Config: configs/textrecog/nrtr/nrtr_r31_1by8_1by4_academic.py
    Metadata:
      Training Data:
        - SynthText
        - Syn90k
    Results:
      - Task: Text Recognition
        Dataset: IIIT5K
        Metrics:
          word_acc: 95.2
      - Task: Text Recognition
        Dataset: SVT
        Metrics:
          word_acc: 90.0
      - Task: Text Recognition
        Dataset: ICDAR2013
        Metrics:
          word_acc: 94.0
      - Task: Text Recognition
        Dataset: ICDAR2015
        Metrics:
          word_acc: 74.1
      - Task: Text Recognition
        Dataset: SVTP
        Metrics:
          word_acc: 79.4
      - Task: Text Recognition
        Dataset: CT80
        Metrics:
          word_acc: 88.2
    Weights: https://download.openmmlab.com/mmocr/textrecog/nrtr/nrtr_r31_1by8_1by4_academic_20211123-e1fdb322.pth
