[atmos-common]
debugSwitch=0 #0表示关，1表示开
subTypes="svc" #支持的sub类型
[atmos-svc]
sub="svc"
lb="svc_lb"
defaultTimeout=3000  #单位毫秒,默认超时时间
engineTimeout=3000  #单位毫秒,调用引擎接口超时时间（单次调用）
getEngineResultTimeout=15 #单位秒，获取引擎结果的时候，最大等待时间(可能包含多次引擎接口调用 )
mockSwitch=0 #0表示mock，1表示正常
engineRetry=2#调用引擎失败重试次数

[log]
level = "info"  #日志等级。可设置参数debug、info、warn、error。缺省warn。
file = "/log/server/atmos.log"    #业务日志路径。
size = 100      #日志大小。单位MB。缺省100
count = 20      #日志文件留存数量。缺省20。
die = 10        #日志文件的有效期。单位天。缺省10。
#async = 1       #是否启用异步日志。1是0否。缺省1。
#cache = -1      #日志缓存大小。单位条数，超过会丢弃。缺省-1，代表不丢数据，存到内存中。
#batch = 100     #触发写时间的日志条目数，超过会触发落盘事件。缺省16000。
#caller = 0      #是否添加调用行信息。1是0否。缺省0。