#服务自身的配置
#注意此section名需对应bootConfig中的service
[atmos]#已做缺省处理
host = "172.16.154.172"#若host为空，则取netcard对应的ip，若二者均为空，则取hostname对应的ip
#netcard = "eth0"
port = 50062
reuseport = 1 #缺省0
cmdserver = 1 #缺省0
finder = 1 #缺省0
debug = 0 #缺省0

#trace日志所用
[trace]#已做缺省处理
#trace收集服务的地址
host = "127.0.0.1" #缺省127.0.0.1
#trace收集服务的端口
port = 4546 #缺省4545
#trace服务的协程数
backend = 1 #缺省4
#是否将日志写入到远端
deliver = 0 #缺省1
#是否将日志 落入磁盘
dump = 1 #缺省0
#是否禁用trace
able = 0 #缺省1
spill = "/log/spill"  #缺省/log/spill
buffer =    1000000 #缓冲,缺省1000000
batch =     100     #大小,缺省100
linger =    5       #每几秒检查一次buffer,缺省5

[log]#已做缺省处理
level = "info" #缺省warn
file = "/log/xsfs.log" #缺省xsfs.log
#日志文件的大小，单位MB
size = 300 #缺省10
#日志文件的备份数量
count = 3 #缺省10
#日志文件的有效期，单位Day
die = 3 #缺省10
#缓存大小，单位条数,超过会丢弃
cache = 100000 #缺省-1，代表不丢数据，堆积到内存中
#批处理大小，单位条数，一次写入条数（触发写事件的条数）
batch = 160#缺省16*1024
#异步日志
async = 0 #缺省异步
#是否添加调用行信息
caller = 1 #缺省0
wash = 60 #写入磁盘的缺省时间